# Loads default set of integrations. Do not remove.
default_config:

notify:
  - platform: group
    name: "colin_and_allys_phones"
    services:
      - service: mobile_app_colins_iphone
      - service: mobile_app_iphone_286

command_line:
  - sensor:
      name: GPT Response
      command: 'curl -XPOST https://api.openai.com/v1/chat/completions -H ''Content-Type: application/json'' -H ''Authorization: Bearer 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'' -d ''{"model": "gpt-3.5-turbo-16k", "messages": [{"role": "user","content": "Imagine you are writing a message to your girlfriend before she drives to work in the morning. Make the message silly, with agriculture, farming, or tiny house puns."}], "top_p": 1, "temperature": 2, "frequency_penalty": 0.49, "max_tokens": 155, "presence_penalty": 1.07}'''
      value_template: "{{ value_json.choices[0].message.content }}"
      scan_interval: 100

input_text:
  greeting_message:
    name: Greeting Message
    initial: How are you doing today?

# Text to speech
tts:
  - platform: google_translate

light:
  - platform: group
    name: Bedroom Downlights
    entities:
      - light.bedroom_downlight_1
      - light.bedroom_downlight_2
      - light.bedroom_downlight_3
      - light.bedroom_downlight_4
  - platform: group
    name: Living Room Downlights
    entities:
      - light.living_room_downlight_1
      - light.living_room_downlight_2
      - light.living_room_downlight_3
      - light.living_room_downlight_4
  - platform: group
    name: Bedside Lights
    entities:
      - light.right_of_bed
      - light.left_of_bed
python_script:

##### Spotcast settings ##################################
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: NL #optional, added in 3.6.24

lovelace:
  resources:
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
plant: !include plants.yaml
group: !include groups.yaml
stream:
frontend:
  themes: !include_dir_merge_named themes

shell_command:
  suppress_sid_to_n8n: curl -X POST -d "suppress_sid={{ states('input_text.suppress_sid')}}" http://{{ states('input_text.n8n_ip')}}:5678/webhook/458f4422-8029-417f-8ce7-0924c0b2fbc4
