# Loads default set of integrations. Do not remove.
default_config:

notify:
  - platform: group
    name: "colin_and_allys_phones"
    services:
      - service: mobile_app_colins_iphone
      - service: mobile_app_iphone_286

input_text:
  greeting_message:
    name: Greeting Message
    initial: How are you doing today?

# Text to speech
tts:
  - platform: google_translate

light:
  - platform: group
    name: Bedroom Downlights
    entities:
      - light.bedroom_downlight_1
      - light.bedroom_downlight_2
      - light.bedroom_downlight_3
      - light.bedroom_downlight_4
  - platform: group
    name: Living Room Downlights
    entities:
      - light.living_room_downlight_1
      - light.living_room_downlight_2
      - light.living_room_downlight_3
      - light.living_room_downlight_4
  - platform: group
    name: Bedside Lights
    entities:
      - light.right_of_bed
      - light.left_of_bed
python_script:

##### Spotcast settings ##################################
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: NL #optional, added in 3.6.24

lovelace:
  resources:
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
plant: !include plants.yaml
group: !include groups.yaml
stream:
frontend:
  themes: !include_dir_merge_named themes

