- platform: template
  sensors:
    set_thermostat_temp:
      friendly_name: "Temp Thermostat Set To"
      unit_of_measurement: "째F"
      value_template: "{{ state_attr('climate.thermostat', 'temperature') }}"
    my_thermostat_temperature:
      friendly_name: "My Thermostat Tempurature"
      unit_of_measurement: "째F"
      value_template: "{{ state_attr('climate.thermostat', 'current_temperature') }}"
    outside_temperature:
      friendly_name: "Outside Temperature"
      unit_of_measurement: "째F"
      value_template: "{{ state_attr('weather.home', 'temperature') }}"
    forecast_low_today:
      friendly_name: "Forecast Low Today"
      unit_of_measurement: "째F"
      value_template: "{{ state_attr('weather.home', 'forecast')[0]['templow'] }}"

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"

- platform: rest
  resource: !secret geo_key
  name: ip_geo_location
  scan_interval: 300
  value_template: "OK"
  json_attributes:
    - moonrise
    - moonset
    - moon_altitude
